# Generated by Django 2.2.28 on 2022-11-25 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multiply', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='seconds',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=7),
        ),
    ]
