# Generated by Django 2.2.28 on 2022-11-26 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multiply', '0002_auto_20221125_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='winner',
            field=models.BooleanField(default=False),
        ),
    ]
